version: '3'
services:
  artifactory:
    image: docker.bintray.io/jfrog/artifactory-oss:6.23.13
    container_name: artifactory
    ports:
     - 8081:8081
    volumes:
     - /data/jfrog/storage:/var/opt/jfrog/artifactory
    restart: always
    ulimits:
      nproc: 65535
      nofile:
        soft: 32000
        hard: 40000
